# Copyright (c) 2016-2025 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Geral ===========================================================================================
site_name: Jix - AQWorlds Handbook
site_url: https://jix-aqw.github.io/site/
site_author: Arthur Calafange & Marcel 'PineOak' Carvalho
site_description: >-
  Vídeos, tutoriais, walkthroughs e muito mais!

# Repositorio =====================================================================================

#repo_name: jix-AQW/site
#repo_url: https://github.com/jix-AQW/site
edit_uri: edit/main/docs/

# Copyright =======================================================================================

copyright: Copyright &copy; 2025 - Arthur Calafange & Marcel 'PineOak' Carvalho

# Configuração ====================================================================================

theme:
  name: material
  language: pt
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.path
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: fontawesome/solid/moon
        name: Trocar para modo Escuro 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: fontawesome/solid/sun
        name: Trocar para modo Claro
  font:
    text: Roboto
    code: Roboto Mono
  logo: logo.png
  icon:
    edit: material/pencil 
    view: material/eye

# Navegação ===================================================================================================
#
# Plugins ====================================================================================================

plugins:
  #- obsidian-interactive-graph:
  #- rss:
  - awesome-nav:  
  #- git-committers:
  #    repository: jix-AQW/site
  #    branch: main
  - table-reader:
  #- git-revision-date-localized:
  #    enable_creation_date: true
  - blog:
      enabled: true
      blog_dir: jornal
      post_date_format: medium # Jan 31, 2024
      post_url_date_format: yyyy/MM
      blog_toc: true
      categories_allowed:
        - Novidade
        - Video
        - Tutorial
        - Walkthrough
  - offline:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  - autorefs:
# Configurações Extras ==================================================================== 
extra_css:
  - https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.min.css
  - assets/stylesheets/interactive_graph.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js
  - assets/javascripts/interactive_graph.js
  - https://cdn.jsdelivr.net/npm/@widgetbot/crate@3
  - assets/js/discord.js  # Arquivo local com a inicialização
extra:
  robots.txt: robots.txt  # Se estiver na pasta "docs/"
  #alternate:
  #  - name: Português
  #    link: /pt/ 
  #    lang: pt
  #  - name: English
  #    link: /en/
  #    lang: en
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: G-MS5X0B1DTN
    feedback:
      title: Esta página foi útil?
      ratings:
        - icon: material/thumb-up-outline
          name: Sim
          data: 1
          note: Obrigado pelo feedback!
        - icon: material/thumb-down-outline
          name: Não
          data: 0
          note: Ajude-nos a melhorar <a href="https://discord.gg/uc9y27NYTp">enviando sugestões</a>.
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@jixaqw
    - icon: fontawesome/brands/whatsapp
      link: https://chat.whatsapp.com/Lau9dPjAkxL...
    - icon: fontawesome/brands/discord
      link: https://discord.gg/uc9y27NYTp
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/jixaqw
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Jix-AQW/site
  consent:
    title: Cookie consent
    description: >- 
      Nós usamos cookies para reconhecer suas visitas repetidas e preferências, assim como para medir a eficácia da nossa documentação e se os usuários encontram o que estão procurando. Com seu consentimento, você nos ajuda a tornar nossa documentação melhor..
# Exclusões ===================================================================================================
exclude:
  - assets/templates/**
# Extensões =====================================================================================
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: jix0aqw
      repo: site
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


