# .github/workflows/deploy.yml
name: Deploy Docs
on:
  push:
    branches: [main]

# PERMISSÕES ADICIONADAS AQUI ↓
permissions:
  contents: write  # Permite escrever no branch gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessário para o mkdocs gh-deploy

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install mkdocs mkdocstrings mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-git-committers-plugin-2 mkdocs-table-reader-plugin mkdocs-glightbox

      # Configura o Git corretamente ↓
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}  # Segredo obrigatório
        run: mkdocs gh-deploy --force
        
      - name: Verificar substituição
        run: |
          echo "Chave GA: ${{ secrets.GOOGLE_ANALYTICS_KEY }}"
          mkdocs build --verbose
          grep -rin "G-" site/*  # Procura o ID no HTML gerado
